name: galley
version: 0.5.0
description: Helm chart for galley deployment
keywords:
  - istio
  - galley
sources:
  - http://github.com/istio/istio
engine: gotpl
icon: https://istio.io/favicons/android-192x192.png
