apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: udsver-client
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: udsver-client
        version: v1
    spec:
      securityContext:
        fsGroup: 0
      containers:
      - name: udsver-client
        image: gcr.io/istio-testing/workload:latest
        imagePullPolicy: IfNotPresent
        command: ["/main"]
        args: ["--sock", "/tmp/udsver/nodeagent/server.sock" ]
        volumeMounts:
        - mountPath: /tmp/udsver
          name: test-volume
      volumes:
        - name: test-volume
          flexVolume:
            driver: nodeagent/uds
