dependencies:
  - name: sidecar-injector
    version: 0.8.0
    # repository: file://../sidecar-injector
    condition: sidecar-injector.enabled
  - name: ingress
    version: 0.8.0
    # repository: file://../ingress
    condition: ingress.enabled
  - name: ingressgateway
    version: 0.8.0
    # repository: file://../ingressgateway
    condition: ingressgateway.enabled
  - name: egressgateway
    version: 0.8.0
    # repository: file://../egressgateway
    condition: egressgateway.enabled
  - name: mixer
    version: 0.8.0
    # repository: file://../mixer
    condition: mixer.enabled
  - name: pilot
    version: 0.8.0
    # repository: file://../pilot
    condition: pilot.enabled
  - name: grafana
    version: 0.1.0
    # repository: file://../addons/grafana
    condition: grafana.enabled
  - name: prometheus
    version: 0.1.0
    # repository: file://../addons/prometheus
    condition: prometheus.enabled
  - name: servicegraph
    version: 0.1.0
    # repository: file://../addons/servicegraph
    condition: servicegraph.enabled
  - name: zipkin
    version: 0.1.0
    # repository: file://../addons/zipkin
    condition: zipkin.enabled
  - name: galley
    version: 0.8.0
    # repository: file://../sidecar-injector
    condition: galley.enabled
