apiVersion: v1
kind: Endpoints
metadata:
  name: istio-policy
  namespace: istio-system
subsets:
- addresses:
  - ip: {{ .Values.global.policyEndpoint }}
  ports:
  - name: tcp-plain
    port: 9091
  - name: tcp-mtls
    port: 15004
  - name: http-monitoring
    port: 9093
  - name: configapi
    port: 9094
  - name: statsd-prom
    port: 9102
  - name: statsd-udp
    port: 9125
    protocol: UDP
  - name: prometheus
    port: 42422
---
apiVersion: v1
kind: Endpoints
metadata:
  name: istio-pilot
  namespace: istio-system
subsets:
- addresses:
  - ip: {{ .Values.global.pilotEndpoint }}
  ports:
  - port: 15011
    name: https-xds
  - port: 15003
    name: http-old-discovery
  - port: 15005
    name: https-discovery
  - port: 15007
    name: http-discovery
  - port: 15010
    name: grpc-discovery
  - port: 8080
    name: http-legacy-discovery
  - port: 9093
    name: http-monitoring
  - port: 443
    name: admission-webhook
---
